/**
 * Generated by UML-to-Java compiler, version 1.0 beta
 * from F:\Test\apps\a1\units\include\helloworld.uml
 * Wednesday, 2025-10-15 11:08:13
 */
public class ErrorQuestionMark {
    public static void main(String[] args) {
        System.out.print("Hell");
        System.out.println("o world");
    }
}
