@startuml
skinparam classAttributeIconSize 0
hide circle

class Complex {
 - a : double
 - b : double
 + Complex(a : double, b : double)
 + Complex()
 + toString() : String <<override>>
}

class TestComplex {
 + {static} main(args : String[])
}

TestComplex - Complex

@enduml
