@startuml
skinparam classAttributeIconSize 0
hide circle

package fractal {
class Mandelbrot {
  - {static}file : File
  - width : int
  - height : int
  - icount : int
  - zoom : double
  - nextY : int
  - colors : int[][] <<width x height>>
  + Mandelbrot(width : int, height : int, icount : int, zoom : double, threads : int)
  + {static}main(args : String[])
  + calculateImage()
  + worker(threadID : int)
  + nextY() : int <<synchronized>>
  + calculateRow(y : int)
  + calculatePoint(x : int, y : int)
  + toString() : String <<override>>
}
}

package complex {
class Complex {
  - x : double
  - y : double
--
  + Complex(x : double, y : double)
  + Complex()
  + Complex(in : Scanner)
  + save(out : PrintStream)
..
  + getReal() : double
  + getImaginary() : double
..
  + abs() : double
  + theta() : double
  + scale(alpha : double) : Complex
  + conjugate() : Complex
  + reciprocal() : Complex
..
  + plus(c : Complex) : Complex
  + minus(c : Complex) : Complex
  + times(c : Complex) : Complex
  + divide(c : Complex) : Complex
..
  + exp() : Complex
  + sin() : Complex
  + cos() : Complex
  + tan() : Complex
..
  + toString() : String <<override>>
  + equals(o : Object) : boolean <<override>>
  + hashCode() : int <<override>>
}
}

Mandelbrot -> Complex
@enduml
